name: tdesign_flutter
description: TDesign 适配移动端的组件库，适合在 flutter 技术栈项目中使用。
version: 0.0.2
homepage: https://github.com/Kigoal/tdesign_flutter

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.4
  provider: ^6.1.1
  tdesign_icons_flutter: ^1.0.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
